export const IMAGES = {
  APP_HEADER_LOGO: "./images/common/horizontal-logo.png",
  HOME_BANNER: "./images/banner/home.jpeg",
  SERVICES_BANNER: "./images/banner/services.jpeg",
  ABOUT_BANNER: "./images/banner/about.jpeg",
  CONTACT_BANNER: "./images/banner/contact.jpeg",

  HOME_ABOUT_US: "./images/home/about-header.jpeg",

  CAROUSEL_CONSULTATION_ROOM: "./images/carousel/consultation-room.jpeg",
  CAROUSEL_DENTSPLY_SIRONA: "./images/carousel/dentsply-sirona.jpeg",
  CAROUSEL_LOBBY_AREA: "./images/carousel/lobby-area.jpeg",
  CAROUSEL_ORTHOPHOS_SL: "./images/carousel/orthophos-sl.jpeg",
  CAROUSEL_RECEPTION_AREA: "./images/carousel/reception-area.jpeg",
  CAROUSEL_SNACK_AREA: "./images/carousel/snack-area.jpeg",

  SERVICE_DENTAL_CONSULTATION: "./icon/dental-consultation.svg",
  SERVICE_LATEST_TECHNOLOGY: "./icon/latest-technology-1.svg",
  SERVICE_MISSING_TEETH_AND_DENTAL:
    "./icon/missing-teeth-and-dental-implants.svg",
  SERVICE_PAEDIATRIC_DENTISTRY: "./icon/paediatric-dentistry.svg",
  SERVICE_PREVENTIVE: "./icon/preventitive-dentistry-pain-management.svg",
  SERVICE_RESTORATIVE: "./icon/restorative-cosmetic-surgery.svg",
  SERVICE_TEETH_STRAIGHTENING: "./icon/teeth-straightening.svg",
  SERVICE_XRAY_SCANNING: "./icon/xray-scanning.svg",

  SERVICE_INFO_1: "./images/services/1.png",
  SERVICE_INFO_2_1: "./images/services/2.1.png",
  SERVICE_INFO_2: "./images/services/2.png",
  SERVICE_INFO_3: "./images/services/3.png",
  SERVICE_INFO_3_1: "./images/services/3.1.png",
  SERVICE_INFO_3_2: "./images/services/3.2.png",
  SERVICE_INFO_4: "./images/services/4.png",
  SERVICE_INFO_4_1: "./images/services/4.1.png",
  SERVICE_INFO_5: "./images/services/5.png",
  SERVICE_INFO_5_1: "./images/services/5.1.png",
  SERVICE_INFO_5_2: "./images/services/5.2.png",
  SERVICE_INFO_5_3: "./images/services/5.3.png",
  SERVICE_INFO_5_4: "./images/services/5.4.png",
  SERVICE_INFO_6: "./images/services/6.png",
  SERVICE_INFO_6_1: "./images/services/6.1.png",
  SERVICE_INFO_7: "./images/services/7.png",
  SERVICE_INFO_7_1: "./images/services/7.1.png",
  SERVICE_INFO_7_2: "./images/services/7.2.png",
  SERVICE_INFO_8: "./images/services/8.png",
};
